### ISSUE TITLE
Your Readme is incorrect

### ISSUE THREAD

**Issue by dabobert** [elfenars/itunes_parser#1]
I believe you are specifying the wrong param for initializes the object.  One should do:
`ip = ItunesParser.new(file: "/route/to/the/file.xml")`
not 
`ip = ItunesParser.new(xml_dir: "/route/to/the/file.xml")`

**Comment by rojosinalma** [comment]
true, I'll fix it

**Comment by rojosinalma** [comment]
Fixed in 51c0e0b9
